version: "3.8"
services:

  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_ROOT_PASSWORD=tlc
      - MYSQL_DATABASE=tlc
      - MYSQL_USER=tlc
      - MYSQL_PASSWORD=tlc
  etherpad:
    image: etherpad/etherpad:stable
    ports:
      - "9001:9001"
    volumes:
      - ./api/APIKEY.txt:/opt/etherpad-lite/APIKEY.txt
  mail:
    image: bytemark/smtp
    restart: always
    ports:
      - "2525:25"
  quarkus-back:
    build: ./api
    ports:
      - "8080:8080"
    depends_on:
      - db
      - mail
      - etherpad
  fronttlc:
    container_name: fronttlc-container
    build: ./front
    ports: 
      - "4200:4200"
    command: > 
      bash -c "npm install && ng serve --host 0.0.0.0 --port 4200"
    depends_on:
      - quarkus-back
