version: '3'

services:
  mywww:
    image: bunkerity/bunkerized-nginx
    restart: always
    ports:
      - 80:8080
      - 443:8443
    volumes:
      - ./front/dist/tlcfront:/www
      - ./letsencrypt:/etc/letsencrypt
      - ./server-confs:/server-confs:ro         # custom confs at server context for permalinks
    environment:
      # Ensemble des endpoints pour lequel il générera des certificats
      - SERVER_NAME=ouluteam.diverse-team.fr
      - SERVE_FILES=yes
      - DISABLE_DEFAULT_SERVER=no
      # Transmission de l'IP publique vers les containers
      - PROXY_REAL_IP=yes
      #- MAX_CLIENT_SIZE=100m
      #- USE_ANTIBOT=captcha
      # Configuration de letencrypt
      - AUTO_LETS_ENCRYPT=yes
      # redirect du 80 vers 443 automatique
      - REDIRECT_HTTP_TO_HTTPS=yes
      - USE_LIMIT_REQ=no
      # Désactivation http2
      - HTTP2=no
      # Paramétrage des entêtes http
      - FEATURE_POLICY=accelerometer 'none'; ambient-light-sensor 'none'; autoplay 'none'; camera 'none'; display-capture 'none'; document-domain 'none'; encrypted-media 'none'; fullscreen 'none'; geolocation 'none'; gyroscope 'none'; magnetometer 'none'; microphone 'none'; midi 'none'; payment 'none'; picture-in-picture 'none'; speaker 'none'; sync-xhr 'self'; usb 'none'; vibrate 'none'; vr 'none'
    networks:
      - api_shared-net

networks:
  api_shared-net:
    external: true
